# pull official base image
FROM node:21.6.0

# set working directory
WORKDIR /azmi_oualid_site

# add `/app/node_modules/.bin` to $PATH
ENV PATH /azmi_oualid_site/node_modules/.bin:$PATH

COPY . ./

RUN npm install 

RUN npm run build

EXPOSE 6006

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]